name: Test

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  setup-just:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install just
        uses: taiki-e/install-action@v2
        with:
          tool: just

      - name: Verify Just Installation
        run: just --version

  clippy:
    runs-on: ubuntu-20.04
    needs: setup-just

    steps:
      - uses: actions/checkout@v4
      - name: Run lint
        run: just lint

  cargo-fmt:
    runs-on: ubuntu-20.04
    needs: setup-just

    steps:
      - uses: actions/checkout@v4
      - name: Run fmt
        run: just fmt

  cargo-doc:
    runs-on: ubuntu-20.04
    needs: setup-just

    steps:
      - uses: actions/checkout@v4
      - name: Run cargo doc
        run: RUSTDOCFLAGS="-D warnings" cargo doc

  test:
    needs: [setup-just, cargo-fmt] 
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        toolchain: [stable]
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v2
      - name: "${{ matrix.toolchain }}"
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          default: true
      - uses: foundry-rs/foundry-toolchain@v1
      - uses: Swatinem/rust-cache@v1
      - name: Add wasm32 target
        run: rustup target add wasm32-unknown-unknown
      - name: Check with stable features
        run: just check
      - name: Run tests
        run: just test
