name: Test

on:
  push:
    branches: [ main ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Run clippy
      run: cargo clippy --all-targets -- -D clippy::all -D clippy::nursery
